version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - DJANGO_SETTINGS_MODULE=admin.settings
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQl_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
